const queries = {
    addNewUser: "insert into dbo.Usuarios(id, nombre, apellido, fecha_nacimiento, email, password, fecha_creacion, img_url_profile, tipo_usuario, estado_usuario) values (@id, @nombre, @apellido, @fecha_nacimiento, @email, @password, @fecha_creacion, @img_url_profile, @tipo_usuario, @estado_usuario)",
    addNewScenario: "insert into dbo.escenarios(id, nombre_escenario, num_likes, num_dislikes, img_url) values (@id, @nombre_escenario, @num_likes, @num_dislikes, @img_url)",
    addNewComment: "insert into dbo.comentarios(id, texto, escenario_id, usuario_id, fecha_creacion) values (@id, @texto, @escenario_id, @usuario_id, @fecha_creacion)",
    addNewSuggest: "insert into dbo.sugerencias(id, tipo_sugerencia, comentario_sugerencia, fecha_creacion, usuario_id) values (@id, @tipo_sugerencia, @comentario_sugerencia, @fecha_creacion, @usuario_id)",
    addNewSession: "insert into dbo.sesiones(id, fecha_creacion, usuario_id, nombre_sesion, medico_id) values (@id, @fecha_creacion, @usuario_id, @nombre_sesion, @medico_id)",
    addNewClinicNote: "insert into dbo.notas_clinicas(id, sesion_id, descripcion) values(@id, @sesion_id, @descripcion)",
    addNewPlan: "insert into dbo.planes(id, fecha_creacion, especialista_id, paciente_id, descripcion_plan, nombre_plan) values(@id, @fecha_creacion, @especialista_id, @paciente_id, @descripcion_plan, @nombre_plan)",
    addNewGoal: "insert into dbo.metas (id, plan_id, descripcion, estado_meta) values (@id, @plan_id, @descripcion, @estado_meta)",
    addNewFavoriteScenario: "insert into dbo.escenarios_favoritos(id, usuario_id, escenario_id) values (@id, @usuario_id, @escenario_id)",
    addNewCommentChild: "insert into dbo.comentarios(id, texto, escenario_id, usuario_id, fecha_creacion, comentario_padre_id) values (@id, @texto, @escenario_id, @usuario_id, @fecha_creacion, @comentario_padre_id)",
    addNewFeedback: "insert into dbo.feedbacks (id, usuario_id, feedback_descripcion, velocidad_de_habla, contacto_visual, palabras_de_filtro, facilidad_de_escucha, score) values (@id, @usuario_id, @feedback_descripcion, @velocidad_de_habla, @contacto_visual, @palabras_de_filtro, @facilidad_de_escucha, @score)",
    addNewQuestionnaireGeneral: "INSERT INTO cuestionario_general (id,usuario_id,fecha_creacion, pregunta_1, pregunta_2, pregunta_3, pregunta_4, pregunta_5, pregunta_6, pregunta_7, pregunta_8, pregunta_9, pregunta_10, pregunta_11, pregunta_12, pregunta_13, pregunta_14, pregunta_15) VALUES (@id, @usuario_id, @fecha_creacion, @pregunta_1, @pregunta_2, @pregunta_3, @pregunta_4, @pregunta_5, @pregunta_6, @pregunta_7, @pregunta_8, @pregunta_9, @pregunta_10, @pregunta_11, @pregunta_12, @pregunta_13, @pregunta_14, @pregunta_15)",
    addNewQuestionnairePreSocial: "INSERT INTO dbo.cuestionario_presocial (id,usuario_id,fecha_creacion, pregunta_1, pregunta_2, pregunta_3, pregunta_4, pregunta_5, pregunta_6, pregunta_7, pregunta_8, pregunta_9, pregunta_10, pregunta_11, pregunta_12, pregunta_13, pregunta_14) VALUES (@id, @usuario_id, @fecha_creacion, @pregunta_1, @pregunta_2, @pregunta_3, @pregunta_4, @pregunta_5, @pregunta_6, @pregunta_7, @pregunta_8, @pregunta_9, @pregunta_10, @pregunta_11, @pregunta_12, @pregunta_13, @pregunta_14)",
    addNewQuestionnairePostSocial: "INSERT INTO dbo.cuestionario_postsocial (id,usuario_id,fecha_creacion, pregunta_1, pregunta_2, pregunta_3, pregunta_4, pregunta_5, pregunta_6, pregunta_7, pregunta_8, pregunta_9, pregunta_10, pregunta_11, pregunta_12, pregunta_13, pregunta_14) VALUES (@id, @usuario_id, @fecha_creacion, @pregunta_1, @pregunta_2, @pregunta_3, @pregunta_4, @pregunta_5, @pregunta_6, @pregunta_7, @pregunta_8, @pregunta_9, @pregunta_10, @pregunta_11, @pregunta_12, @pregunta_13, @pregunta_14)",
    addNewQuestionnairePreEntrevista: "INSERT INTO dbo.cuestionario_preentrevista (id,usuario_id,fecha_creacion, pregunta_1, pregunta_2, pregunta_3, pregunta_4, pregunta_5, pregunta_6, pregunta_7, pregunta_8, pregunta_9, pregunta_10, pregunta_11, pregunta_12, pregunta_13, pregunta_14) VALUES (@id, @usuario_id, @fecha_creacion, @pregunta_1, @pregunta_2, @pregunta_3, @pregunta_4, @pregunta_5, @pregunta_6, @pregunta_7, @pregunta_8, @pregunta_9, @pregunta_10, @pregunta_11, @pregunta_12, @pregunta_13, @pregunta_14)",
    addNewQuestionnairePostEntrevista: "INSERT INTO dbo.cuestionario_postentrevista (id,usuario_id,fecha_creacion, pregunta_1, pregunta_2, pregunta_3, pregunta_4, pregunta_5, pregunta_6, pregunta_7, pregunta_8, pregunta_9, pregunta_10, pregunta_11, pregunta_12, pregunta_13, pregunta_14) VALUES (@id, @usuario_id, @fecha_creacion, @pregunta_1, @pregunta_2, @pregunta_3, @pregunta_4, @pregunta_5, @pregunta_6, @pregunta_7, @pregunta_8, @pregunta_9, @pregunta_10, @pregunta_11, @pregunta_12, @pregunta_13, @pregunta_14)"
}

export default queries